version: '3'

services:
  db:
    image: mysql
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dbnetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - "db:db"
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - dbnetwork
networks:
  dbnetwork:
